/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal.frontend.gui.calendari_cholquij;

import principal.backend.calendari_cholquij.calcular_fecha.CalcularFecha;
import principal.backend.manejadores.ManejadorInformacion;
import principal.frontend.gui.calendari_cholquij.matriz.matrizCholquijFrame;

/**
 *
 * @author bryangmz
 */
public class FrameCalendario extends javax.swing.JFrame {

    private matrizCholquijFrame frame;
    private ManejadorInformacion manejadorInformacion = ManejadorInformacion.getInstancia();
    
    /**
     * Creates new form FrameCalendario
     */
    public FrameCalendario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnMatrizCalendario2 = new javax.swing.JButton();
        btnCalendarioLunar = new javax.swing.JButton();
        btnMatrizCalendario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setBackground(new java.awt.Color(0, 0, 0));
        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("CALENDARIO CHOLQ'IJ");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 470, 70));

        btnMatrizCalendario2.setBackground(new java.awt.Color(51, 51, 51));
        btnMatrizCalendario2.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        btnMatrizCalendario2.setForeground(new java.awt.Color(204, 204, 204));
        btnMatrizCalendario2.setText("Nahual - Energia Cholq'ij");
        btnMatrizCalendario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatrizCalendario2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMatrizCalendario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 290, -1));

        btnCalendarioLunar.setBackground(new java.awt.Color(51, 51, 51));
        btnCalendarioLunar.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        btnCalendarioLunar.setForeground(new java.awt.Color(204, 204, 204));
        btnCalendarioLunar.setText("Calcular Fecha Cholq'ij");
        btnCalendarioLunar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalendarioLunarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalendarioLunar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 290, -1));

        btnMatrizCalendario.setBackground(new java.awt.Color(51, 51, 51));
        btnMatrizCalendario.setFont(new java.awt.Font("Waree", 1, 18)); // NOI18N
        btnMatrizCalendario.setForeground(new java.awt.Color(204, 204, 204));
        btnMatrizCalendario.setText("Informacion Cholq'ij");
        btnMatrizCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMatrizCalendarioActionPerformed(evt);
            }
        });
        getContentPane().add(btnMatrizCalendario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 290, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/principal/frontend/gui/calendari_cholquij/Portada.png"))); // NOI18N
        jLabel1.setText(" ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 590));

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setForeground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N

        jMenu1.setBackground(new java.awt.Color(51, 51, 51));
        jMenu1.setForeground(new java.awt.Color(204, 204, 204));
        jMenu1.setText("Calendario Lunar");
        jMenu1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setBackground(new java.awt.Color(51, 51, 51));
        jMenu3.setForeground(new java.awt.Color(204, 204, 204));
        jMenu3.setText("Cholq'ij");
        jMenu3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jMenu4.setText("Forma de Contar");
        jMenu4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenu4);

        jMenu5.setText("Días");
        jMenu5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu3.add(jMenu5);

        jMenu6.setText("Calendario");
        jMenu6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenu3.add(jMenu6);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        //Menu Calendario Lunar
        manejadorInformacion.mostrarInfCalendarioLunar();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        //Menu formas de contar
        manejadorInformacion.mostarInfFormasDeContar();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
       //Dias del Cholquij
       manejadorInformacion.mostrarInfDiasCholquij();
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
        //menu mostrar infromacion cholquij
        manejadorInformacion.mostrarInfCholquij();
    }//GEN-LAST:event_jMenu6MouseClicked

    private void btnCalendarioLunarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalendarioLunarActionPerformed
        // TODO add your handling code here:
        CalcularFecha calcularFecha = new CalcularFecha(this, true);
        calcularFecha.setVisible(true);
    }//GEN-LAST:event_btnCalendarioLunarActionPerformed

    private void btnMatrizCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatrizCalendarioActionPerformed
        // TODO add your handling code here:
        if (frame == null) {
            frame = new matrizCholquijFrame();
        }
        frame.setVisible(true);
    }//GEN-LAST:event_btnMatrizCalendarioActionPerformed

    private void btnMatrizCalendario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMatrizCalendario2ActionPerformed
        // TODO add your handling code here:
        CholqijFrame cholqijFrame = new CholqijFrame();
        cholqijFrame.setVisible(true);
    }//GEN-LAST:event_btnMatrizCalendario2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalendarioLunar;
    private javax.swing.JButton btnMatrizCalendario;
    private javax.swing.JButton btnMatrizCalendario2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
